# Generated by Django 3.1.1 on 2020-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201106_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='audio_description',
            field=models.FileField(null=True, upload_to='blog/audio/'),
        ),
    ]
